---
functional:
  - Сайт должен иметь возможность создания пробной игры без регистрации/авторизации
  - На сайте должна быть возможность открыть гайд с описанием функционала в созданной игре (Show guide)
  - На сайте должна быть возможность выбора языка описания задания игры (русский, английский)
  - Пользователь должен иметь возможность выбора языка программирования в игре 
  - Пользователь должен иметь возможность запуска написанного кода (Run)
  - Пользователь должен иметь возможность отправлять сообщения в чат игры  
  - Пользователь должен иметь возможность сдаться во время игры (Give up)
  - Пользователь должен иметь возможность просматривать рейтинг игроков в LEADERBOARD
  - Пользователь должен иметь возможность присоединиться к просмотру турнира других игроков 
  - Пользователь должен видеть окно с анимацией в случае выигрыша/проигрыша
  - Пользователь-победитель должен иметь возможность выхода из игры
  - Пользователь-проигравший должен иметь возможность доиграть до конца
  - Игры считается полностью законченной после выхода обоих игроков  
  - Пользователь должен иметь возможность сменить язык программирования в настройках профиля
  - Пользователь может создать клан в настройках профиля  
  - В профиле пользователя можно просмотреть спиисок завершённых игр во вкладке "Completed games"  
  - Пользователь может открыть страницу создания новой задачи для Codebattle
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)  
implicit:
  - Пользователь должен иметь личный кабинет на сайте
  - Пользователь должен иметь возможность просмотра истории в игре
  - Никнейм должен содержать от 3 до 16 символов
  - Никнейм может содержать латиницу, цифры, нижнее подчёркивание



    
    
    
